* Sorbae

** Installation

Clone this repository and add the lisp directory to your load path.
Then, require it and go.

#+BEGIN_SRC emacs-lisp
    (add-to-list 'load-path "/path/to/sorbae/lisp")
    (require 'sorbae)
#+END_SRC

** Usage

Once the ~sorbae~ library has been loaded you can use the ~sorbae-mwtm~  and ~sorbae-insert-multi~ to render brand codes to brand names.


The following is an example of how to use Sorbae.

Open ~*scratch*~ and insert the following. Each ~sorbae-mwtm~ will make a table for a single seizure form. ~sorbae-insert-mulit~ concatenates all seizure tables and inserts it in the current buffer at your current ~(point)~.

#+BEGIN_SRC emacs-lisp
(sorbae-insert-multi
  (sorbae-mwtm
    "Inspector A" "Estamlishment 1" "Region 0" "2019-10-1"
    GW 3 SA 2 SG 5 SG 5 SA 3 GW 4)
  (sorbae-mwtm
    "Inspector B" "Establishment 2" "Region 0" "2019-11-1"
    SA 1)
  (sorbae-mwtm
    "Inspector C" "Establishment 3" "Region 0" "2019-11-01"
    PG 1 PG 1 SG 2 SG 2 SG 1 SA 2 PA 1 BK 1 BK 2 BK 1 AB 1 AB 2 ML 1 ML 1
    ML 1 ML 2 ML 1 PA 2 SA 1 SA 2 BK 1 BK 1 BK 2 SG 2 SG 2 PO 1 PO 2 PO 1
    GW 1 GW 1 GW 1 PF 1 PF 1))
#+END_SRC

Navigate to the end of the inserted data and execute it using `C-M-x`. The table below should be inserted at ~(point)~. You can go ahead and insert this ~csv~ data into excel.

#+BEGIN_SRC csv
Inspector A,Estamlishment 1,Region 0,2019-10-1,Sorbae Grapefruit Watermelon, 3
,,,,Sorbae Raspberry Sour Apple, 2
,,,,Sorbae Strawberry Guava, 5
,,,,Sorbae Strawberry Guava, 5
,,,,Sorbae Raspberry Sour Apple, 3
,,,,Sorbae Grapefruit Watermelon, 4
Inspector B,Establishment 2,Region 0,2019-11-1,Sorbae Raspberry Sour Apple, 1
Inspector C,Establishment 3,Region 0,2019-11-01,Sorbae Pineapple Guava, 1
,,,,Sorbae Pineapple Guava, 1
,,,,Sorbae Strawberry Guava, 2
,,,,Sorbae Strawberry Guava, 2
,,,,Sorbae Strawberry Guava, 1
,,,,Sorbae Raspberry Sour Apple, 2
,,,,Sorbae Peach Apricot, 1
,,,,Sorbae Blueberry Kiwi, 1
,,,,Sorbae Blueberry Kiwi, 2
,,,,Sorbae Blueberry Kiwi, 1
,,,,Sorbae Apple Berry, 1
,,,,Sorbae Apple Berry, 2
,,,,Sorbae Mango Lychee, 1
,,,,Sorbae Mango Lychee, 1
,,,,Sorbae Mango Lychee, 1
,,,,Sorbae Mango Lychee, 2
,,,,Sorbae Mango Lychee, 1
,,,,Sorbae Peach Apricot, 2
,,,,Sorbae Raspberry Sour Apple, 1
,,,,Sorbae Raspberry Sour Apple, 2
,,,,Sorbae Blueberry Kiwi, 1
,,,,Sorbae Blueberry Kiwi, 1
,,,,Sorbae Blueberry Kiwi, 2
,,,,Sorbae Strawberry Guava, 2
,,,,Sorbae Strawberry Guava, 2
,,,,Sorbae Pomegranate Orange, 1
,,,,Sorbae Pomegranate Orange, 2
,,,,Sorbae Pomegranate Orange, 1
,,,,Sorbae Grapefruit Watermelon, 1
,,,,Sorbae Grapefruit Watermelon, 1
,,,,Sorbae Grapefruit Watermelon, 1
,,,,Sorbae Passion Fruit Aloe, 1
,,,,Sorbae Passion Fruit Aloe, 1
#+END_SRC

** Future
- [ ] Better ~csv~ formating. Right now strings are not encompased by ~""~.
- [ ] Convert this to an excel macro. 
